#!/bin/sh
# KTEX installer. One command, nothing to upload to the Kindle:
#
#   curl -sL <this-url> | sh
#
# This file never changes. It resolves the current version at run time, so new
# releases arrive without the URL changing. Do not edit this file; it is
# generated by make-installer.py.

KTEX_ROOT="${KTEX_ROOT:-/mnt/us}"
APP_DIR="$KTEX_ROOT/ktex"
SCRIPTLET="$KTEX_ROOT/documents/KTEX.sh"
WORK="$KTEX_ROOT/ktex-install-tmp"
REPO_URLS="https://heinrich-xiao.github.io/ktex-kpm https://cdn.jsdelivr.net/gh/Heinrich-XIAO/ktex-kpm@main https://raw.githubusercontent.com/Heinrich-XIAO/ktex-kpm/main"
FALLBACK_VERSIONS="0.3.2 0.3.1 0.3.0 0.2.2 0.2.1"

say() { echo "KTEX: $1"; }
die() { say "$1"; exit 1; }

get() {
    # get <url> <destination>. Timeouts matter: a Kindle on flaky wifi must fail
    # fast and try the next mirror instead of hanging.
    if command -v curl >/dev/null 2>&1; then
        curl -fsL --connect-timeout 8 -m 90 "$1" -o "$2" && return 0
    fi
    if command -v wget >/dev/null 2>&1; then
        wget -q -T 20 -O "$2" "$1" && return 0
    fi
    return 1
}

json_field() {
    tr ',' '\n' < "$1" | grep "\"$2\"" | head -1 | cut -d '"' -f4
}

rm -rf "$WORK"
mkdir -p "$WORK" || die "cannot write to $KTEX_ROOT"

# ---- ask every mirror which version is current -----------------------------------
say "looking for the latest version..."
STAMP="$(date +%s 2>/dev/null || echo 0)"
FOUND=""
for base in $REPO_URLS; do
    for u in "$base/latest.json?cb=$STAMP" "$base/latest.json"; do
        if get "$u" "$WORK/latest.json" && [ -s "$WORK/latest.json" ]; then
            v="$(json_field "$WORK/latest.json" version)"
            p="$(json_field "$WORK/latest.json" payload)"
            if [ -n "$v" ] && [ -n "$p" ]; then
                FOUND="$FOUND$v $base/$p
"
                break
            fi
        fi
    done
done

# Highest reported version wins (numeric, not string: 0.2.10 > 0.2.9).
BEST="$(printf '%s' "$FOUND" | awk 'NF {
    if (best == "") { best = $1; line = $0; next }
    n = split($1, a, "."); m = split(best, b, ".")
    if ((a[1]+0) > (b[1]+0) ||
        ((a[1]+0) == (b[1]+0) && (a[2]+0) > (b[2]+0)) ||
        ((a[1]+0) == (b[1]+0) && (a[2]+0) == (b[2]+0) && (a[3]+0) > (b[3]+0))) {
        best = $1; line = $0
    }
} END { print line }')"

# ---- download: winner first, then a few recent fallbacks --------------------------
TGZ="$WORK/payload.tgz"
CHOSEN=""

try_url() {
    rm -f "$TGZ"
    if get "$1" "$TGZ" && [ -s "$TGZ" ]; then
        CHOSEN="$1"
        return 0
    fi
    return 1
}

BEST_VER="$(echo "$BEST" | cut -d ' ' -f1)"
BEST_URL="$(echo "$BEST" | cut -d ' ' -f2)"

if [ -n "$BEST_URL" ]; then
    say "downloading $(basename "$BEST_URL")"
    try_url "$BEST_URL"
fi

if [ -z "$CHOSEN" ]; then
    COUNT=0
    for v in $FALLBACK_VERSIONS; do
        [ -n "$v" ] || continue
        [ "$v" = "$BEST_VER" ] && continue
        COUNT=$((COUNT + 1))
        [ "$COUNT" -gt 3 ] && break
        for base in $REPO_URLS; do
            if try_url "$base/payload-$v.tgz"; then
                say "downloaded payload-$v.tgz"
                break
            fi
        done
        [ -n "$CHOSEN" ] && break
    done
fi

[ -n "$CHOSEN" ] || die "could not download any payload (check WiFi)"
say "installing $(basename "$CHOSEN") (version $(basename "$CHOSEN" | sed -e 's/^payload-//' -e 's/[.]tgz$//'))"
say "downloaded $(wc -c < "$TGZ" | tr -d ' ') bytes"

# ---- unpack -----------------------------------------------------------------------
# /mnt/us is vfat: no symlinks, and some tars abort on them. Extract
# best-effort, then extract any missing files individually.
rm -rf "$APP_DIR"
mkdir -p "$APP_DIR" || die "cannot create $APP_DIR"
( cd "$APP_DIR" && tar xzf "$TGZ" 2>/dev/null )

missing=""
for want in app/index.html app/ktex.js app/style.css server.py launch.sh; do
    [ -f "$APP_DIR/$want" ] || missing="$missing $want"
done
if [ -n "$missing" ]; then
    say "some files were missing, extracting them individually"
    for want in $missing; do
        ( cd "$APP_DIR" && tar xzf "$TGZ" "$want" 2>/dev/null )
    done
fi
for want in app/index.html server.py launch.sh; do
    [ -f "$APP_DIR/$want" ] || die "payload is missing $want"
done
chmod +x "$APP_DIR/launch.sh" 2>/dev/null
chmod +x "$APP_DIR/server.py" 2>/dev/null

# ---- library scriptlet -------------------------------------------------------------
mkdir -p "$KTEX_ROOT/documents" || die "cannot create $KTEX_ROOT/documents"
cat > "$SCRIPTLET" <<'SCRIPTLET'
#!/bin/sh
# Name: KTEX LaTeX Pad
# Author: ktex
KTEX_ROOT="${KTEX_ROOT:-/mnt/us}"
exec sh "$KTEX_ROOT/ktex/launch.sh"
SCRIPTLET
chmod +x "$SCRIPTLET"

rm -rf "$WORK"
say "installed to $APP_DIR"
say "starting..."
sh "$APP_DIR/launch.sh"
